# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      # - image: circleci/node:10.6.0
       - image: circleci/node:12.18.2

    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install

      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "divya_bhushan@hotmail.com"
            git config --global user.name "divyabhushan"
            echo "machine github.com login divyabhushan password $GITHUB_TOKEN" > ~/.netrc
            GIT_USER=divyabhushan yarn deploy            

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master